---
- name: Remove the Ansible Runner Instance
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    key_name: ansible_runner
    region: ap-southeast-1
    image: ami-0df7a207adb9748c7
    id: "ansible-runner"
    sec_group: "{{ id }}-sec"

  tasks:
    - name: Get the info of ec2 instance
      amazon.aws.ec2_instance_info:
        filters:
          "tag:Name": "{{ id }}"
        region: "{{ region }}"
      register: ec2_info

    - name: Display information about ec2
      ansible.builtin.debug:
        msg: "{{ item.instance_id }}"
      with_items: "{{ ec2_info.instances }}"

    - name: Terminate the instance EC2
      amazon.aws.ec2_instance:
        instance_ids:
          - "{{ item.instance_id }}"
        region: "{{ region }}"
        state: absent
        wait: true
      with_items: "{{ ec2_info.instances }}"

    - name: Delete the sec_group
      amazon.aws.ec2_security_group:
        name: "{{ sec_group }}"
        region: "{{ region }}"
        state: absent

    - name: Delete the ec2 ssh key
      amazon.aws.ec2_key:
        name: "{{ key_name }}"
        region: "{{ region }}"
        state: absent
